### ISSUE TITLE
Short summary of my code reading: Brief Introduction to Rack

### ISSUE THREAD

**Issue by tomykaira** [codereading/rack#10]
I got through all of the rack codes.  I summarize my impression into a markdown document.
The notation about code itself is shorthanded now, but I will add figures to get better understand.

https://gist.github.com/2731566

Let me know if there are problem either technically or grammatically.

P.S.
Can I open a new issue for such notification, or is there a better issue to comment on?

**Comment by agis** [comment]
Nice!
